title: Abderrahim Jami Portfolio
author: Abderrahim Jami
email: abderrahimjami@live.it
description: > # this means to ignore newlines until "baseurl:"
  Hello, this is the description of my website, testing... testing, 1, 2, 3... 
  testing

# social links
twitter_username: jamiab123 # DO NOT include the @ character, or else the build will fail!
github_username:  abderrahimjami1700081 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
